# docker-compose up --build
version: '2.4'
services:
  analysis_worker:
    build: # only necessary if rebuilding image
      context: .
      dockerfile: calcium_imaging_worker.Dockerfile
      args:
        - PY_VER
        - DIST
        - DEPLOY_KEY
        - REPO_OWNER
        - REPO_NAME
    image: registry.vathes.com/sciops/analysis-${REPO_NAME}:py${PY_VER}-${DIST}-v${WORKFLOW_VERSION}
    environment:
      - CONTAINER_USER
      - DJ_HOST
      - DJ_USER
      - DJ_PASS
      - DATABASE_PREFIX
      - AWS_ACCESS_KEY
      - AWS_ACCESS_SECRET
      - IMAGING_ROOT_DATA_DIR=/home/${CONTAINER_USER}/inbox
      - IMAGING_PROCESSED_DATA_DIR=/home/${CONTAINER_USER}/outbox
    volumes:
      - ${IMAGING_ROOT_DATA_DIR}:/home/${CONTAINER_USER}/inbox
      - ${IMAGING_PROCESSED_DATA_DIR}:/home/${CONTAINER_USER}/outbox
    scale: ${WORKER_COUNT:-1}
    command:
      - /bin/bash
      - -c
      - |
        run_workflow calcium_imaging_worker &
        tail -f /dev/null
